name: Kusagiri-RDP

on: workflow_dispatch

jobs:
  build:

    runs-on: windows-2019
    timeout-minutes: 9999

    steps:
    - name: Downloading Ngrok.
      run: |
        Invoke-WebRequest https://raw.githack.com/Kusagiri0/files/main/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githack.com/Kusagiri0/files/main/start.bat -OutFile start.bat
        Invoke-WebRequest https://raw.githack.com/Kusagiri0/files/main/wallpaper.png -OutFile wallpaper.bmp
        Invoke-WebRequest https://raw.githack.com/Kusagiri0/files/main/wallpaper.bat -OutFile wallpaper.bat
    - name: Downloading Launcher.
      run: |
        Invoke-WebRequest https://raw.githack.com/Kusagiri0/files/main/launcher/Node.js.lnk -OutFile Node.js.lnk
        Invoke-WebRequest https://raw.githack.com/Kusagiri0/files/main/launcher/AnimeBatchRename_0.1.3.exe -OutFile "AnimeBatchRename_0.1.3.exe"
        Invoke-WebRequest https://raw.githack.com/Kusagiri0/files/main/launcher/npp.7.6.6.Installer.x64.exe -OutFile "npp.7.6.6.Installer.x64.exe"
        Invoke-WebRequest https://raw.githack.com/Kusagiri0/files/main/launcher/winrar-x64-570.exe -OutFile "winrar-x64-570.exe"
    - name: Extracting Ngrok File.
      run: Expand-Archive ngrok.zip
    - name: Connect To Ngrok Account.
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Activated RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        copy wallpaper.bmp D:\a\wallpaper.bmp
        copy wallpaper.bat D:\a\wallpaper.bat
        copy Node.js.lnk C:\Users\Public\Desktop\Node.js.lnk
        copy AnimeBatchRename_0.1.3.exe C:\Users\Public\Desktop\AnimeBatchRename_0.1.3.exe
        copy npp.7.6.6.Installer.x64.exe C:\Users\Public\Desktop\npp.7.6.6.Installer.x64.exe
        copy winrar-x64-570.exe C:\Users\Public\Desktop\winrar-x64-570.exe
        
    - name: Creating Tunnel.
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp --region ap 3389"'
    - name: Connect to your RDP CPU 2 Core - 7GB Ram - 255 SSD.
      run: cmd /c start.bat
    - name: Success Create! You can close tab now.
      run: | 
        Invoke-WebRequest https://raw.githack.com/Kusagiri0/files/main/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
